name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['5.0.x' ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
            # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
              ${{ runner.os }}-nuget
      - name: Install dependencies
        run: dotnet restore
      - name: Install dependencies
        run: dotnet add package Newtonsoft.Json --version 3.1.4
      - name: Install dependencies
        run: dotnet add package EntityFrameworkCore.Design --version 5.0.1
      - name: Install dependencies
        run: dotnet add package Authentication.JwtBearer --version 3.1.4
      - name: Install dependencies
        run: dotnet add package EntityFrameworkCore.Sqlite --version 5.0.1
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
